{% set name = "large-image-converter" %}
{% set version = "1.8.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e77396fbbbb8adda2d8271a8729ef013c6fca6c873255d06463af8a579003bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - large-image =={{ version }}
    - large-image-source-gdal =={{ version }}
    - large-image-source-tiff =={{ version }}
    - pyvips
    - tifftools
    - glymur
    - scikit-image

test:
  imports:
    - large_image
    - large_image_source_gdal
    - large_image_source_tiff
    - large_image_converter

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images - converter.
  description: |
    Python modules to work with large, multiresolution images - converter. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
