{% set name = "large-image-converter" %}
{% set version = "1.32.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8cef1eac4e434f81193b2d53f2e82a5c9a3da9113c3382f8303c8e6e480a416c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - large-image
    - large-image-source-gdal
    - large-image-source-tiff
    - pyvips
    - tifftools
    - scikit-image

test:
  requires:
    - python {{ python_min }}
  imports:
    - large_image
    - large_image_source_gdal
    - large_image_source_tiff
    - large_image_converter

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images - converter.
  description: |
    Python modules to work with large, multiresolution images - converter. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
