{% set name = "large-image-converter" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1fcf2243e82161a99d2bd901d4210c649fa6ef38ef4d76659bf73326ca79111b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - large-image
    - large-image-source-gdal
    - large-image-source-tiff
    - pyvips
    - tifftools
    - glymur
    - scikit-image

test:
  imports:
    - large_image
    - large_image_source_gdal
    - large_image_source_tiff
    - large_image_converter

about:
  home: https://github.com/girder/large_image
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python modules to work with large, multiresolution images - converter.
  description: |
    Python modules to work with large, multiresolution images - converter. Large Image is developed and maintained by the Data & Analytics group at Kitware, Inc. for processing large geospatial and medical images.
  doc_url: https://girder.github.io/large_image/
  dev_url: https://github.com/girder/large_image

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
